export enum NotificationTypeEnum { 
    COMMUNITY_DISCUSSION_REPLY  = 'COMMUNITY_DISCUSSION_REPLY',
    COMMUNITY_CHILD_REPLY = 'COMMUNITY_CHILD_REPLY',
    COMMUNITY_DISCUSSION_VOTED_UP = 'COMMUNITY_DISCUSSION_VOTED_UP',
    COMMUNITY_REPLY_VOTED_UP = 'COMMUNITY_REPLY_VOTED_UP',
    COMMUNITY_MENTIONED = 'COMMUNITY_MENTIONED'
}

